sync contents to latest release
jboss-container-images/jboss-amq-6-openshift-image pull request #55
Opened 2018-07-23 14:18 UTC by gaohoward

Signed-off-by: Howard Gao <howard.gao@gmail.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

2018-07-23 14:19 UTC, gaohoward commented
@goldmann Hi Marek,
This is the sync PR for openshift cp branch. Please review.
Thanks
Howard

2018-07-23 14:30 UTC, goldmann requested changes
Please update the branch.

2018-07-23 14:30 UTC, goldmann commented on image.yaml
>              branch: ce-1.3-openshift-amq-6.3-jdk-8-rhel-7
Branch is different too: `jb-amq-6.3-openshift-rhel-7`. The suggestion is that the branch in the image image descriptor is pointing to the "main" target branch, but the specific one (`jb-amq-6.3-openshift-cp-rhel-7`) is added to an override file.

2018-07-23 14:37 UTC, gaohoward commented
OK I'll change it. Btw in the actual building, is it ok just to use --override option in the command-line?
Howard

2018-07-24 14:29 UTC, gaohoward commented
@goldmann Just changed to sprint-21.

2018-07-24 14:35 UTC, goldmann approved these changes

2018-07-31 07:50 UTC, merged